hook: "cp -f '$W' ~/Pictures/wallpapers/pacwall.png;"
"hsetroot -solid '#3b4252' -center '$W'"
shell: "sh"

attributes: {
	graph: "size='9.5,9.5';bgcolor='#00000000'"
	package: {
		common: "fontname='mononoki Nerd Font',fontcolor='#d8dee9',fontsize=11"
		implicit: "shape=point,color='#81a1c1aa'"
		explicit: "shape=plaintext,color='#a3be8c',fontsize=7"
		outdated: "shape=plaintext,color='#ebcb8b',fontcolor='#bf616a'"
		orphan: "shape=plaintext,color='#d08770',fontcolor='#d08770'"
		unneded: "shape=plaintext,color='#bf616a',fontcolor='#bf616a'"
	}
	dependency: {
		common: "color='#4c566a4a',arrowhead=empty,arrowsize=0.75,arrowtail=none"
	}
}
