eval %sh{kak-lsp --kakoune -s %val{session}}
kakboard-enable

hook global WinSetOption filetype=(rust|javascript|typescript|c|cpp) %{
	set global lsp_cmd "kak-lsp -s %val{session} -vvv --log /tmp/kak-lsp.log"
    lsp-enable-window
	lsp-inlay-diagnostics-enable window
	map -docstring "Lsp hover" window user "k" ":lsp-hover<ret>"
	map -docstring "Enter lsp mode" window user "l" ":enter-user-mode lsp<ret>"
}

# Options
set-option current tabstop 4
set-option current indentwidth 0
