eval %sh{kak-lsp --kakoune -s %val{session}}

hook global WinSetOption filetype=(rust|javascript|typescript|c|cpp|zig) %{
	set global lsp_cmd "kak-lsp -s %val{session} -vvv --log /tmp/kak-lsp.log"
    lsp-enable-window
	lsp-inlay-diagnostics-enable window
	map -docstring "Lsp hover" window user "k" ":lsp-hover<ret>"
	map -docstring "Enter lsp mode" window user "l" ":enter-user-mode lsp<ret>"
}
hook global WinSetOption filetype=(scheme) %{
	map global user s ":repl-send-text<ret>" -docstring "Send text to the repl"
}

set-option current indentwidth 2

addhl global/ show-matching
