#!/bin/bash

desktops=$(xdotool get_num_desktops)
focusdesktop=$(xdotool get_desktop)
output=""

for i in $(seq 0 $( expr $desktops - 1))
do
  if [[ $i == $focusdesktop ]]
  then
    output="$output %{+u}%{F#ECEFF4}%{B#3B4252} · %{B-}%{F-}%{-u}"
    continue
  fi

  output="$output·"
done

echo $output | tr -d "\n"
