# vim: ft=config

backend = "glx";

##################
# Shadows
#################
shadow = false;
shadow-radius = 8;

shadow-offset-x = -3;
shadow-offset-y = -3;

shadow-exclue = [
	"class_g != 'Notification'",
]

################
# Opacity rules
################
opacity-rule = [
  "95:class_g = 'Termite' && focused", 
  "80:class_g = 'Termite' && !focused",
  "95:class_g = 'St' && focused", 
  "80:class_g = 'St' && !focused",
];

inactive-opacity = 1.0;
active-opacity = 1.0;

###############
# Transition
###############
transition-length = 200;
transition-pow-x = .1;
transition-pow-y = .1;
size-transition = true;

##################
# Rounded corners
##################
corner-radius = 0;
rounded-corners-exclude = [
  "class_g = 'Bar'",
  "class_g = 'dmenu'",
  "class_g = 'Dunst'"
]

#########
# Blur
########
blur: {
	method = "kawase";
}
