#!/bin/bash

export PAGER="less"
export MANPAGER="nvim -c 'set ft=man'"

export LESSHISTFILE=".cache/less/history"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export GNUPGHOME="$XDG_DATA_HOME/.gnupg"
export PATH=$PATH:~/.local/bin
export SKIM_DEFAULT_OPTIONS="--height=70% --reverse --tiebreak=score,end,length,index --prompt=\"λ \""
HISTFILE=~/.cache/bash/zshhistory
export PS1=" \e[36m\w\e[37;2m>\e[0m\n \e[32mλ \e[0m"

# generic fuzzer
gf () {
	f="$(eval $1 | sk)"
	[[ -n $f ]] && $2 $f
}

alias nf="gf 'fd -t f' 'nvim'"
alias cf="gf 'fd -t d' 'cd'"
alias of="gf 'fd -t f' 'xdg-open'"

af () {
	output=$(sk -e --ansi -c "ag '{}' --color" -i)
	line="$(echo $output | cut -d: -f2)"
	file="$(echo $output | cut -d: -f1)"
	nvim -c "set nofoldenable" "+$line" "$file"
}

alias n="nvim"
alias tsm="transmission-remote"
alias zthr="zathura"

alias nj="ninja"
alias njb="ninja -C build"
alias mb="meson build"
alias mc="meson configure build"

# git aliases
alias ga="git add"
alias gb="git branch"
alias gc="git commit"
alias gch="git checkout"
alias gd="git diff"
alias gr="git reset"
alias grm="git rm"
alias gs="git status"

alias cp="cp -i"
alias rm="rm -i"

DISABLE_AUTO_TITLE="true"
touch /dev/shm/pwd
chpwd () {
  echo -en "\e]0;bash:\W\a"
  pwd > /dev/shm/pwd
}
cd $(cat /dev/shm/pwd)

#nordic tty?
if [[ $TERM = "linux" ]]
then
	echo -en "\e]P02E3440"
	echo -en "\e]P1BF616A"
	echo -en "\e]P2A3BE8C"
	echo -en "\e]P3EBCB8B"
	echo -en "\e]P481A1C1"
	echo -en "\e]P5B48EAD"
	echo -en "\e]P688C0D0"
	echo -en "\e]P7D8DEE9"
	echo -en "\e]P84C566A"
	echo -en "\e]P9BF616A"
	echo -en "\e]PAA3BE8C"
	echo -en "\e]PBEBCB8B"
	echo -en "\e]PC81A1C1"
	echo -en "\e]PDB48EAD"
	echo -en "\e]PE8FBCBB"
	echo -en "\e]PFD8DEE9"

	clear
fi
