#!/bin/bash

#####################
# Initialize log
#####################
mkdir -p ~/.cache/wm
echo > ~/.cache/wm/log
exec > ~/.cache/wm/log 2>&1
echo -e "\\e[34m\\e[1m::\\e[37m Initialized bspwm log...\\e[0m"

#########################################
# create lock so only one instance can exist
#########################################
test -e ~/.cache/wm/rc.lck && exit
touch ~/.cache/wm/rc.lck

#####################
# set up enviornment
#####################
echo -e "\\e[34m\\e[1m::\\e[37m Setting up environment variables...\\e[0m"

export EDITOR=nvim
export BROWSER=firefox
export TERMINAL=alacritty
export USER_SHELL=bash
export SHELL=sh

export PASSWORD_STORE_DIR=~/.local/password-store
export LESSHISTFILE=~/.cache/lesshst
export GNUPGHOME=~/.local/share/gnupg

# if $1 is greater than 1 that means this is not run for the first time
test $1 -gt 1 && (
	echo -e "\\e[34m\\e[1m::\\e[37m killing duplicate processess..\\e[0m"
	killall "picom" \
		"sxhkd" \
		"lemonbar" \
		"controllemonbar" \
		"dunst" \
		"xcape" \
		"pipewire" \
		"pipewire-pulse" \
		"wireplumber"
)

# wallpaper
echo -e "\\e[34m\\e[1m::\\e[37m Setting wallpaper...\\e[0m"
hsetroot -solid '#2e3440' -fill ~/Pictures/wallpapers/fill.png -center ~/Pictures/wallpapers/center.png &

echo -e "\\e[34m\\e[1m::\\e[37m Configuring X...\\e[0m"
xrandr -s 1366x768
xsetroot -cursor_name left_ptr
xset r rate 250 100

# map keys
xcape -e Super_L=Escape

# load xresources
echo -e "\\e[34m\\e[1m::\\e[37m Loading Xresources...\\e[0m"
xrdb ~/.config/Xresources/main # load Xresources

#####################
# daemons
#####################
echo -e "\\e[34m\\e[1m::\\e[37m Starting daemons...\\e[0m"

SHELL=bash test $1 -gt 1 && (sxhkd &) || sxhkd -m 1 &
picom --experimental-backend &
dunst &

( controllemonbar | \
lemonbar -gx15 -f"Iosevka:pixelsize=13:antialias=true" -B#2e3440 -F#d8dee9 -U#88c0d0 -o2 ) &

pipewire &
pipewire-pulse &
wireplumber &

#####################
# bspwm settings
#####################
echo -e "\\e[34m\\e[1m::\\e[37m Configuring bspwm...\\e[0m"

bspc config border_width					0
bspc config window_gap						1
bspc config left_padding					0
bspc config right_padding				0
bspc config bottom_padding				0
bspc config top_padding					15

bspc config split_ratio          		0.50
bspc config automatic_scheme         longest_side
bspc config directional_focus_tightness low

bspc config focus_follows_pointer    true
bspc config pointer_follows_focus    false
bspc config pointer_follows_monitor  true

# resize stuff
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

#####################
# bspwm rules
#####################
echo -e "\\e[34m\\e[1m::\\e[37m Setting window rules...\\e[0m"

bspc rule -a Screenkey manage=off
bspc rule -a Notes state=floating sticky=on
bspc rule -a firefox:\*:Picture-in-Picture state=floating sticky=on

# force some windows into tiling mode
bspc rule -a gimp state=tiling
bspc rule -a Zathura state=tiling

#####################
# finish
#####################
echo -e "\\e[34m\\e[1m::\\e[37m Finished\\e[0m"

rm ~/.cache/wm/rc.lck # clean up lock
