#!/bin/sh

link="$(xclip -selection clipboard -o)"

curl -s -F "shorten=$link" 0x0.st | xclip -selection clipboard -i -r

dunstify -a Sxhkd "Shortened $link" "shortened version of $link is in the clipboard"
