#!/bin/bash

MENU_FILE=~/.config/menus/applications.menu

rdom () { local IFS=\> ; read -d \< E C ;}

parse_menu ()  {
	# skip the first <Menu>
	rdom && rdom

	directorydirs=""
	appdirs=""
	menuname=""
	menus=""

	while rdom
	do
		case "$E" in
			"/Menu")
				break
				;;
			"Name")
				menuname="$C"
				;;
			"Directory")
				directorydirs="$directorydirs $C"
				;;
			"AppDir")
				appdirs="$appdirs $C"
				;;
			"DefaultAppDirs/")
				appdirs="$appdirs /usr/share/applications /usr/local/share/applications"
				;;
			"Menu")
				ret=$( ( echo "<Menu>"
				while rdom
				do
					test $E = "/Menu" && break
					echo -n "<$E>$C"
				done
				echo "</Menu>" ) | parse_menu )
				menus="$menus $ret"
				;;
			*)
				;;
		esac
	done

	echo -en "$menus\n$menuname"
}

cat $MENU_FILE | parse_menu
echo $something
