#!/bin/bash

error () {
	dunstify -a screenshot "Error" "$1"
}

options="
1: select an area and take a screenshot to clipboard
\n2: select an area and save screenshot to file
"

sel=$(echo -en $options | dmenu -p "screenshot:" -l 15 -i)
test -z "$sel" && dunstify -a screenshot "No option was selected" "Exiting without doing anything" && exit

case $(echo $sel | cut -d\: -f1)
in
	1)
		tmp=$(mktemp -p /tmp/wm screenshot.XXXXXXX || error "failed to create temporary file")
		import "png:$tmp"

		xclip -selection clipboard -t image/png "$tmp"
		rm $tmp

		dunstify -a screenshot "Success!" \
			"The Screenshot was successfully taken, it is in the clipboard."
		;;
	*)
		error "option not implemented yet"
		;;
esac
