#!/bin/bash

dir=/usr/bin
cd $dir

for file in $(fd . $dir)
do
	echo -ne "\e[2K\e[G" 
	echo -n "checking $file"
	if pacman -Qo "$file" &> /dev/null; 
	then
		echo -ne "\e[2K\e[G$file is ok"
	else
		echo -e "\e[2K\e[Gno package owns $file"
		sudo rm -ri $file
	fi
done
