#!/bin/sh

DESKTOPNAME=$(xdotool get_desktop)
DESKTOPNUMS=$(xdotool get_num_desktops)

if test $DESKTOPNAME == $(expr $DESKTOPNUMS - 1)
then
  bspc monitor -a ·
fi

bspc node focused -d next --follow
bspc desktop prev.\!occupied -r
