#!/bin/sh

password_len=$(\
	echo -en "50\n20" | xprompt "enter password length" \
)

pass=$(\
	cat /dev/urandom | tr -cd "!-~[:alpha:]" | head -c "$password_len"\
)

pass_name=$(\
	xprompt "enter password name:"\
)

echo "$pass" | pass insert -e "$pass_name"

dunstify -a pass "Password generation successful!" \
"Your password for '$pass_name' of length $pass_len was succesfully generated. it is in your clipboard"
