#!/bin/sh

sel=$(cat ~/.scripts/xprompt/keyboards.data | xprompt "keyboard:" -i)

lang=$(echo "$sel" | cut -f 1 -d "|")
variant=$(echo "$sel" | cut -f 2 -d "|")

setxkbmap -layout "$lang" -variant "$variant"
