#!/bin/bash

error () {
	herbe "Error" "$1"
}

options="
sel	Select an area
	clip	Load to clipboard
root	Use root
"

sel=$(echo "$options" | xprompt "screenshot:" -i)
test -z "$sel" && herbe "No option was selected" --- "Exiting without doing anything" && exit

case $(echo $sel | cut -d\: -f1)
in
	"sel clip")
		import - | xsel -bi

		herbe "Success!" --- \
			"The Screenshot was successfully taken, it is in the clipboard."
		;;
	*)
		error "option not implemented yet"
		;;
esac
