#!/bin/bash

error () {
	herbe "Error" "$1"
}

options="
1: select an area and take a screenshot to clipboard\n
2: select an area and save screenshot to file
"

sel=$(echo -en $options | xprompt "screenshot:" -i)
test -z "$sel" && herbe "No option was selected" --- "Exiting without doing anything" && exit

case $(echo $sel | cut -d\: -f1)
in
	1)
		tmp=$(mktemp -p /tmp/ screenshot.XXXXXXX || error "failed to create temporary file")
		import "png:$tmp"

		xsel -ci < "$tmp"
		rm $tmp

		herbe"Success!" --- \
			"The Screenshot was successfully taken, it is in the clipboard."
		;;
	*)
		error "option not implemented yet"
		;;
esac
